/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#a1a4ff',
        'surface-container-low': '#f3f4f6',
        'surface-tint': '#4059aa',
        'inverse-on-surface': '#f0f1f3',
        'primary-fixed': '#dce1ff',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'surface-dim': '#d9dadc',
        'on-primary-container': '#90a8ff',
        'secondary-fixed': '#89f5e7',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#edeef0',
        'surface-container-high': '#e7e8ea',
        'secondary-container': '#86f2e4',
        'tertiary-fixed-dim': '#c0c1ff',
        'surface-bright': '#f8f9fb',
        'on-secondary-fixed-variant': '#005049',
        'on-primary-fixed': '#00164e',
        outline: '#757682',
        primary: '#00236f',
        'on-secondary-fixed': '#00201d',
        secondary: '#006a61',
        'on-error-container': '#93000a',
        'primary-container': '#1e3a8a',
        surface: '#f8f9fb',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#b6c4ff',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#6bd8cb',
        'on-secondary-container': '#006f66',
        'outline-variant': '#c5c5d3',
        'tertiary-container': '#2724b8',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e1e2e4',
        'surface-variant': '#e1e2e4',
        'tertiary-fixed': '#e1e0ff',
        'on-surface-variant': '#444651',
        'on-surface': '#191c1e',
        'on-background': '#191c1e',
        'on-tertiary-fixed': '#07006c',
        'inverse-surface': '#2e3132',
        error: '#ba1a1a',
        'inverse-primary': '#b6c4ff',
        'on-primary-fixed-variant': '#264191',
        tertiary: '#0d0097',
        'on-tertiary': '#ffffff',
        background: '#f8f9fb',
        primary: '#002045',
        'surface-dim': '#d7dadc',
        'on-tertiary-fixed-variant': '#00497e',
        'surface-container-low': '#f1f4f6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'unit': '4px',
        'stack-sm': '8px',
        'gutter': '24px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'display-lg': ['Inter'],
        'label-sm': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-md': ['Inter'],
        'body-lg': ['Inter'],
        'title-lg': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
};
